# Site settings
title: ololyay notes
email: denis@aejis.eu
description: > # comment
  Some notes and slides.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ololyay.github.io" # the base hostname & protocol for your site
twitter_username: ololyay
github_username:  ololyay

# Build settings
markdown: kramdown
excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed